# Generated by Django 4.2 on 2023-04-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sales', '0002_alter_city_options_alter_companyaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='tg_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_accounts', to='users.telegramuser'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='sales.region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='subregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='sales.subregion'),
        ),
        migrations.AlterField(
            model_name='salesplacement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.city'),
        ),
        migrations.AlterField(
            model_name='salesplacement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.companyaccount'),
        ),
        migrations.AlterField(
            model_name='salesplacement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.product'),
        ),
        migrations.AlterField(
            model_name='salesplacement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.region'),
        ),
        migrations.AlterField(
            model_name='salesplacement',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.subregion'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='sales.region'),
        ),
    ]
