# Generated by Django 4.2 on 2023-04-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sales', '0003_companyaccount_tg_user_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='tg_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_account', to='users.telegramuser'),
        ),
    ]
