# Generated by Django 4.2 on 2023-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_companyaccount_tg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='код ЄДРПОУ'),
        ),
    ]
