# Generated by Django 4.2 on 2023-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesplacement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesplacement',
            name='currency',
            field=models.CharField(blank=True, choices=[('uah', 'ГРН'), ('usd', 'USD')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='salesplacement',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('posted', 'POSTED'), ('deleted', 'DELETED')], default='draft', max_length=32),
        ),
    ]
