# Generated by Django 4.2 on 2023-04-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesplacement_vat_alter_salesplacement_price_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesplacement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale placement', 'verbose_name_plural': 'Sale Placements'},
        ),
    ]
