# Generated by Django 4.2 on 2023-04-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_salesplacement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_interests', to='sales.companyaccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_interests', to='sales.product')),
            ],
            options={
                'verbose_name': 'Sale Interest',
                'verbose_name_plural': 'Sale Interests',
                'unique_together': {('company', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SalePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('basis', models.CharField(blank=True, max_length=1024, null=True)),
                ('price_type', models.CharField(blank=True, choices=[('f1', 'Ф1'), ('f2', 'Ф2')], max_length=2, null=True)),
                ('vat', models.CharField(blank=True, choices=[('with', 'З ПДВ'), ('without', 'БЕЗ ПДВ')], max_length=7, null=True)),
                ('currency', models.CharField(blank=True, choices=[('uah', 'ГРН'), ('usd', 'USD')], max_length=3, null=True)),
                ('price', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('deleted', 'Deleted')], default='draft', max_length=32)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.city')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.companyaccount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.product')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.region')),
                ('subregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.subregion')),
            ],
            options={
                'verbose_name': 'Sale placement',
                'verbose_name_plural': 'Sale Placements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SalesPlacement',
        ),
    ]
