# Generated by Django 4.2 on 2023-04-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_saleinterest_saleplacement_delete_salesplacement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleInterest',
            new_name='Productnterest',
        ),
        migrations.AlterModelOptions(
            name='productnterest',
            options={'verbose_name': 'Product Interest', 'verbose_name_plural': 'Product Interests'},
        ),
    ]
