# Generated by Django 4.2 on 2023-04-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_rename_saleinterest_productnterest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productnterest',
            new_name='ProductInterest',
        ),
    ]
