# Generated by Django 4.2 on 2023-04-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sales', '0013_rename_productnterest_productinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSaleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=512)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_sales', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Sent Sale Message',
                'verbose_name_plural': 'Sent Sale Messages',
                'unique_together': {('message_id', 'chat')},
            },
        ),
    ]
