# Generated by Django 4.2 on 2023-04-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sales', '0014_sentsalemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsalemessage',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_messages', to='sales.saleplacement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentsalemessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_messages', to='users.telegramuser'),
        ),
    ]
