# Generated by Django 4.2 on 2023-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_sentsalemessage_sale_alter_sentsalemessage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsalemessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
