# Generated by Django 4.2 on 2023-04-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_sentsalemessage_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentsalemessage',
            name='is_deleted',
        ),
    ]
