# Generated by Django 4.2 on 2023-04-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_remove_sentsalemessage_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='sales.subregion'),
        ),
    ]
